const exp=require("express")
const app=express()
const bodyP=require("body-parser")
const compiler=require("compilex")
app.use(bodyP.json())
app.use("/codemirror-5.65.16",express.static("C:/Users/rdeva/Downloads/code blocks/CodeHub/codemirror-5.65.16"))
app.use("/",function(req,res)
{
    res.sendFile("C:/Users/rdeva/Downloads/code blocks/CodeHub/trial.html")
})
app.listen(8000)